apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-deployer
  namespace: mcad
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appwrapper-deployer
rules:
- apiGroups: ["mcad.ibm.com"]
  resources: ["appwrappers"]
  verbs: ["create","get","list","watch","update","patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create","get","list","watch","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appwrapper-deployer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appwrapper-deployer
subjects:
- kind: ServiceAccount
  name: hub-deployer
  namespace: mcad
